version: '3.7'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11400:11400"
    volumes:
      - ./models:/root/.ollama/models
    command: ["ollama", "serve"]

  python-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
      - ollama
    volumes:
      - ./app:/usr/src/app